### ISSUE TITLE
total-items not updating dynamically

### ISSUE THREAD

**Issue by voznik** [sathyapulse/angular-ui-bootstrap-pagination#1]
hi! how can i set `total-items` to update from another scope dynamically? my goal is to rebuild some table with parameters, and i'm watching for some value and set it to `total-items`, but it seems like `total-items` not listening other value.

``` javascript
$scope.$watch('processtype', function(processtype){
...
$http.post('/serv/, dat).then(function(res) {
if (res.data.resultlist.length > 0) {
           $scope.totalItems= res.data.resultlist.length;
......
```

**Comment by sathyapulse** [comment]
Hi @voznik 

I created new pagination plugin, I will create new repository and update the link
